# Usage
# create the db (only the first time)
# docker-compose run web bundle exec rake db:migrate

db:
  image: postgres

web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3002:3000"
  links:
    - db

