# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "wheezy"
  config.vm.box_url = "http://vagrant.cvt.dk/vagrant-wheezy.box"

  config.vm.network :private_network, ip: "192.168.207.18"
  config.vm.hostname = "haitatsu.vagrant.vm"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "haitatsu.vagrant.vm"]
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "init.pp"
    puppet.module_path = ['puppet-applications/vagrant-modules',
      'puppet-applications/modules']
  end
end
